param(
  [string]$InstallDirectory = "D:\WeatherBot\Launcher",
  [switch]$NoDesktopShortcut
)

$ErrorActionPreference = "Stop"

$ProjectRoot = Split-Path -Parent $PSScriptRoot
$SourcePath = Join-Path $ProjectRoot "launcher\WeatherBotLauncher.cs"
$IconSourcePath = Join-Path $ProjectRoot "launcher\assets\weatherbot-launcher.png"
$CompilerCandidates = @(
  "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\csc.exe",
  "C:\Windows\Microsoft.NET\Framework\v4.0.30319\csc.exe"
)
$Compiler = $CompilerCandidates | Where-Object { Test-Path -LiteralPath $_ } | Select-Object -First 1

if (-not $Compiler) {
  throw "Windows .NET Framework C# compiler was not found."
}
if (-not (Test-Path -LiteralPath $SourcePath)) {
  throw "Launcher source was not found: $SourcePath"
}
if (-not (Test-Path -LiteralPath $IconSourcePath)) {
  throw "Launcher icon source was not found: $IconSourcePath"
}
if (-not (Test-Path -LiteralPath "D:\")) {
  throw "D: drive is unavailable. Pass -InstallDirectory to choose another local path."
}

$ResolvedInstallDirectory = [IO.Path]::GetFullPath($InstallDirectory)
New-Item -ItemType Directory -Path $ResolvedInstallDirectory -Force | Out-Null
New-Item -ItemType Directory -Path "D:\WeatherBot\logs" -Force | Out-Null

$ExePath = Join-Path $ResolvedInstallDirectory "WeatherBotLauncher.exe"
$ConfigPath = Join-Path $ResolvedInstallDirectory "WeatherBotLauncher.ini"
$IconPath = Join-Path $ResolvedInstallDirectory "WeatherBotLauncher.ico"

Add-Type -AssemblyName System.Drawing
$SourceImage = [Drawing.Image]::FromFile($IconSourcePath)
$IconSizes = @(256, 64, 48, 32, 16)
$IconImages = @()

try {
  foreach ($Size in $IconSizes) {
    $Bitmap = New-Object Drawing.Bitmap $Size, $Size
    $Graphics = [Drawing.Graphics]::FromImage($Bitmap)
    try {
      $Graphics.Clear([Drawing.Color]::Transparent)
      $Graphics.CompositingQuality = [Drawing.Drawing2D.CompositingQuality]::HighQuality
      $Graphics.InterpolationMode = [Drawing.Drawing2D.InterpolationMode]::HighQualityBicubic
      $Graphics.SmoothingMode = [Drawing.Drawing2D.SmoothingMode]::HighQuality
      $Graphics.PixelOffsetMode = [Drawing.Drawing2D.PixelOffsetMode]::HighQuality
      $Graphics.DrawImage($SourceImage, 0, 0, $Size, $Size)
      $Memory = New-Object IO.MemoryStream
      try {
        $Bitmap.Save($Memory, [Drawing.Imaging.ImageFormat]::Png)
        $IconImages += [pscustomobject]@{
          Size = $Size
          Bytes = $Memory.ToArray()
        }
      } finally {
        $Memory.Dispose()
      }
    } finally {
      $Graphics.Dispose()
      $Bitmap.Dispose()
    }
  }
} finally {
  $SourceImage.Dispose()
}

$IconStream = [IO.File]::Create($IconPath)
$IconWriter = New-Object IO.BinaryWriter $IconStream
try {
  $IconWriter.Write([UInt16]0)
  $IconWriter.Write([UInt16]1)
  $IconWriter.Write([UInt16]$IconImages.Count)
  $Offset = 6 + (16 * $IconImages.Count)
  foreach ($Image in $IconImages) {
    $Dimension = if ($Image.Size -eq 256) { 0 } else { $Image.Size }
    $IconWriter.Write([Byte]$Dimension)
    $IconWriter.Write([Byte]$Dimension)
    $IconWriter.Write([Byte]0)
    $IconWriter.Write([Byte]0)
    $IconWriter.Write([UInt16]1)
    $IconWriter.Write([UInt16]32)
    $IconWriter.Write([UInt32]$Image.Bytes.Length)
    $IconWriter.Write([UInt32]$Offset)
    $Offset += $Image.Bytes.Length
  }
  foreach ($Image in $IconImages) {
    $IconWriter.Write([Byte[]]$Image.Bytes)
  }
} finally {
  $IconWriter.Dispose()
  $IconStream.Dispose()
}

& $Compiler `
  /nologo `
  /target:winexe `
  /optimize+ `
  "/out:$ExePath" `
  "/win32icon:$IconPath" `
  /reference:System.dll `
  /reference:System.Drawing.dll `
  /reference:System.Windows.Forms.dll `
  $SourcePath

if ($LASTEXITCODE -ne 0 -or -not (Test-Path -LiteralPath $ExePath)) {
  throw "WeatherBot launcher compilation failed with exit code $LASTEXITCODE."
}

@"
# Generated by scripts/install_weatherbot_launcher.ps1
ProjectRoot=$ProjectRoot
LogDirectory=D:\WeatherBot\logs
BackendHealthUrl=http://127.0.0.1:8765/api/healthz
SchedulerStartUrl=http://127.0.0.1:8765/api/scheduler/start
DashboardUrl=http://127.0.0.1:5173/
BackendPort=8765
FrontendPort=5173
BackendReadyTimeoutSeconds=300
FrontendReadyTimeoutSeconds=90
StartScheduler=true
"@ | Set-Content -LiteralPath $ConfigPath -Encoding UTF8

$ShortcutPath = $null
if (-not $NoDesktopShortcut) {
  $Desktop = [Environment]::GetFolderPath("Desktop")
  $ShortcutName = "WeatherBot " + [char]0x770B + [char]0x677F + ".lnk"
  $ShortcutPath = Join-Path $Desktop $ShortcutName
  $Shell = New-Object -ComObject WScript.Shell
  $Shortcut = $Shell.CreateShortcut($ShortcutPath)
  $Shortcut.TargetPath = $ExePath
  $Shortcut.WorkingDirectory = $ResolvedInstallDirectory
  $Shortcut.Description = "Start the WeatherBot backend, frontend, scheduler, and dashboard"
  $Shortcut.IconLocation = "$IconPath,0"
  $Shortcut.WindowStyle = 1
  $Shortcut.Save()
}

[pscustomobject]@{
  ok = $true
  compiler = $Compiler
  executable = $ExePath
  config = $ConfigPath
  icon = $IconPath
  desktop_shortcut = $ShortcutPath
  project_root = $ProjectRoot
  log_directory = "D:\WeatherBot\logs"
} | ConvertTo-Json
